kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ template "fullname" . }}
data:
  application.yml: |
    security:
      user:
        name: ${USERNAME:admin}
        password: ${PASSWORD:changeme}
    spring:
      profiles: kubernetes
    zk:
      hosts: zookeeper-service.default.svc.cluster.local:2181
      adminauth: ${ZOOKEEPER_AUTH:super:admin}
    paas:
      servicebroker:
        catalog:
          services:
            - name: zookeeper-service-broker
              id: ${ZK_SERVICE_ID:eef2c9d7-d7df-4abe-b951-f88353dd5d71}
              description: This is zookeeper service broker,support 3.4
              bindable: true
              plan_updatable: true
              tags:
              - zookeeper
              - zk
              metadata:
                displayName: Zookeeper Service
                imageUrl: https://zookeeper.apache.org/images/zookeeper_small.gif
                longDescription: Zookeeper Service Broker
                providerDisplayName: Zookeeper Service Broker
                documentationUrl: https://github.com/wdxxs2z
                supportUrl: https://github.com/wdxxs2z
              plans:
                - name: free
                  id: ${ZK_FREE_PLAN_ID:ca65a33f-6272-4cac-b973-07f0da59f998}
                  bindable: true
                  free: true
                  description: Zookeeper service broker shared.
                  metadata:
                    costs:
                      - amount:
                          usd: 0.0
                        unit: MONTHLY
                    bullets:
                      - Shared ZK server
                      - 40 concurrent connections (not enforced)